@startuml MEMSIM
class Memory {
    - int memory_size
    - byte[] main_memory
    - Segment[] memory_layout

    + Memory(size: int)
    + swap_in(program: Program): void
    + swap_out(layout_index: int): void
    + get_bytes(): byte[]
    + get_memory_layout(): Segment
    + shrink(): void
}

class Segment {
    + string type {readOnly}
    + int index {readOnly}
    + int size {readOnly}
}

class SafeList <<utility>> {
    + __getitem__(index: int) : Any
}

class Program {
    - byte[] bytes

    + Program(bytes: byte[])
    + stream(): byte[]
}

SafeList --|> list
Memory --> Program : uses
Memory --> SafeList : uses
Memory --> Segment : contains
@enduml